pipeline {
    agent any

    /*
    environment {
        backup_dir = '/backup'
        webapp_dir = '/opt/tomcat/webapps'
        war_file_path = "$webapp_dir/*.war"
        jenkins_dir = '/var/lib/jenkins/workspace/MavenPipelineDemo/'
        mavenHome = tool 'jenkins-maven'
        github_repo_url = 'https://github.com/GauravXs/MavenWebApp.git'
        sonarqube_ip = '100.94.222.20'
        sonarqube_port = '9000'
        sonar_host_url = 'http://$sonarqube_ip:$sonarqube_port'
        sonar_login_token = 'sqp_a3aa6db600e70fb06f6afe06c9de7b41bfe03c6b'
        sonar_project_key = 'MavenPipeLineDemo'
    }*/

    tools {
        mavenHome = tool 'jenkins-maven'
        maven 'jenkins-maven'
    }

    stages {

        stage('Build Maven') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: "https://github.com/GauravXs/MavenWebApp.git"]]])
                sh '''
                echo "Pulling from Github Repo"
                cd $jenkins_dir
                ${mavenHome}/bin/mvn clean install
                #mvn -Dmaven.test.failure.ignore=true clean package
                
                '''
                }
            }

        stage("Publish to Nexus Repository Manager") {
            steps {
                script {
                    pom = readMavenPom file: "pom.xml";
                    filesByGlob = findFiles(glob: "target/*.${pom.packaging}");
                    echo "${filesByGlob[0].name} ${filesByGlob[0].path} ${filesByGlob[0].directory} ${filesByGlob[0].length} ${filesByGlob[0].lastModified}"
                    artifactPath = filesByGlob[0].path;
                    artifactExists = fileExists artifactPath;
                    if(artifactExists) {
                        echo "*** File: ${artifactPath}, group: ${pom.groupId}, packaging: ${pom.packaging}, version ${pom.version}";
                        nexusArtifactUploader(
                            nexusVersion: 'nexus3',
                            protocol: 'http',
                            nexusUrl: '100.94.222.20:8081',
                            groupId: 'pom.com.in28minutes',
                            version: 'pom.0.0.1-SNAPSHOT',
                            repository: 'in28Minutes-first-webapp',
                            credentialsId: 'NEXUS_CRED',
                            artifacts: [
                                [artifactId: 'pom.in28Minutes-first-webapp',
                                classifier: '',
                                file: artifactPath,
                                type: pom.packaging],
                                [artifactId: 'pom.in28Minutes-first-webapp',
                                classifier: '',
                                file: "pom.xml",
                                type: "pom"]
                            ]
                        );
                    } else {
                        error "*** File: ${artifactPath}, could not be found";
                    }
                }
            }
        }
        }
}   
